[build-system]
requires = [
    "ninja",
    "packaging",
    "setuptools",
    "torch == 2.3",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
known_first_party = "sarathi"
known_third_party = "wandb"
